#!/bin/bash

git submodule init
git submodule update --recursive --remote

git config --global user.name "Philip Norman"
git config --global user.email "philipnrmn@users.noreply.github.com"

touch $HOME/.secrets

sudo usermod -s "$(which zsh)" "$USER"
