#!/bin/bash

ln -s "$(pwd)/tmux.conf" $HOME/.tmux.conf
ln -s "$(pwd)/vimrc" $HOME/.vimrc
ln -s "$(pwd)/vim"  $HOME/.vim
rm -f $HOME/.zshrc
ln -s "$(pwd)/zshrc" $HOME/.zshrc
ln -s "$(pwd)/zsh" $HOME/.zsh
